import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import heroSneaker from "@/assets/hero-sneaker.jpg";
import { StoreShell } from "@/components/store-shell";
import { ProductCard } from "@/components/product-card";
import { products } from "@/components/store-data";
import { Button } from "@/components/button";

export const Route=createFileRoute("/")({head:()=>({meta:[{title:"BẠO.sneak — Cửa hàng giày trực tuyến"},{name:"description",content:"Mua giày chính hãng theo size, thanh toán COD và theo dõi đơn hàng tại BẠO.sneak."},{property:"og:title",content:"BẠO.sneak — Cửa hàng giày trực tuyến"},{property:"og:description",content:"Chọn giày đúng size, đặt hàng COD nhanh chóng."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Home});
function Home(){const [gender,setGender]=useState("Nam");return <StoreShell><main className="mx-auto max-w-[1440px] px-4 sm:px-6">
 <section className="grid gap-6 pb-4 pt-8 lg:grid-cols-12"><div className="rise flex flex-col justify-between rounded-lg border border-line bg-surface-glass p-7 backdrop-blur-xl lg:col-span-5"><div><span className="rounded-lg bg-coral/15 px-2.5 py-1 font-mono text-[11px] uppercase text-coral">Bộ sưu tập mới · 2026</span><h1 className="mt-5 font-display text-4xl font-bold leading-[.98] sm:text-6xl">Sneaker Việt<br/>chơi lớn,<br/><span className="text-cobalt">mua nhanh.</span></h1><p className="mt-4 max-w-[40ch] text-[15px] text-muted-foreground">Chọn size, thả vào giỏ, nhận hàng trả tiền tại nhà. Đủ hàng, đủ size, đủ hãng.</p></div><div className="mt-6 flex flex-wrap gap-3"><Link to="/products"><Button>Mua ngay</Button></Link><Link to="/categories"><Button variant="outline">Xem danh mục</Button></Link></div></div>
 <div className="rise relative min-h-[380px] overflow-hidden rounded-lg border border-line bg-ice lg:col-span-7"><img src={heroSneaker} alt="Giày cao cổ trắng xanh BẠO Court" width={1280} height={900} className="absolute inset-0 h-full w-full object-cover"/><div className="sheen absolute left-4 top-4 rounded-lg border border-line bg-surface-glass-strong px-3 py-2 backdrop-blur-md"><p className="font-mono text-[10px] uppercase text-muted-foreground">Sản phẩm nổi bật</p><p className="font-display font-bold">BẠO Court 01</p></div><div className="absolute bottom-4 right-4 rounded-lg border border-line bg-surface-glass-strong px-3.5 py-2.5 text-right backdrop-blur-md"><p className="font-mono text-[11px] text-muted-foreground">Giá niêm yết</p><p className="font-display text-xl font-bold">1.290.000₫</p></div></div></section>
 <section className="flex flex-wrap items-center gap-2.5 py-4"><span className="mr-1 font-mono text-[11px] uppercase text-muted-foreground">Danh mục</span>{["Tất cả","Nam","Nữ","Chạy bộ","Cổ điển","Đời thường"].map(c=><button key={c} onClick={()=>setGender(c)} className={`rounded-lg border px-3.5 py-2 text-sm font-medium ${gender===c?"border-ink bg-ink text-primary-foreground":"border-line bg-surface-glass"}`}>{c}</button>)}</section>
 <section className="grid gap-6 pb-10 lg:grid-cols-12"><aside className="h-fit rounded-lg border border-line bg-surface-glass p-5 backdrop-blur-xl lg:col-span-3"><div className="mb-4 flex items-center justify-between"><h2 className="font-display text-lg font-bold">Bộ lọc</h2><button className="font-mono text-[11px] text-cobalt">Xóa</button></div><div className="space-y-5"><Filter title="Thương hiệu" items={["BẠO","Nike","Adidas","Vans"]}/><Filter title="Màu sắc" items={["Trắng","Đen","Xanh","Kem"]}/><div><p className="filter-title">Khoảng giá</p><div className="grid grid-cols-2 gap-2"><input aria-label="Giá từ" placeholder="300.000" className="filter-input"/><input aria-label="Giá đến" placeholder="2.000.000" className="filter-input"/></div></div><div><p className="filter-title">Size</p><div className="grid grid-cols-4 gap-1.5">{[38,39,40,41,42,43,44,45].map(s=><button key={s} className={`h-8 rounded-lg border text-sm ${s===40?"border-ink bg-ink text-primary-foreground":"border-line"}`}>{s}</button>)}</div></div><Button variant="dark" className="w-full">Áp dụng bộ lọc</Button></div></aside>
 <div className="lg:col-span-9"><div className="mb-4 flex items-center justify-between"><p className="text-sm text-muted-foreground">Hiển thị <span className="font-medium text-foreground">12</span> sản phẩm</p><select aria-label="Sắp xếp" className="rounded-lg border border-line bg-surface-glass px-3 py-2 text-sm"><option>Mới nhất</option><option>Giá tăng dần</option><option>Giá giảm dần</option></select></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{products.map(p=><ProductCard key={p.slug} product={p}/>)}</div></div></section>
 </main></StoreShell>}
function Filter({title,items}:{title:string;items:string[]}){return <div><p className="filter-title">{title}</p><div className="space-y-1.5">{items.map((x,i)=><label key={x} className="flex items-center gap-2.5 text-sm"><input type="checkbox" defaultChecked={i===0} className="size-4 accent-cobalt"/>{x}</label>)}</div></div>}
