import { useEffect, useState } from "react";
import { Link, useLocation, useParams } from "react-router";

import { adminProductsApi } from "../../api/admin-products.api.js";
import { useAuth } from "../../auth/useAuth.js";
import { ConfirmDialog } from "../../components/admin/ConfirmDialog.jsx";
import { ImageManager } from "../../components/products/ImageManager.jsx";
import { ProductForm } from "../../components/products/ProductForm.jsx";
import { VariantManager } from "../../components/products/VariantManager.jsx";
import { useDocumentTitle } from "../../hooks/useDocumentTitle.js";

function formValue(product) { return { name: product.name, description: product.description ?? "", material: product.material ?? "", categoryId: product.category.id, brandId: product.brand.id, price: String(product.price), salePrice: product.salePrice === null ? "" : String(product.salePrice), badgeLabel: product.badgeLabel ?? "" }; }

export function AdminProductEditPage() {
  useDocumentTitle("Sửa sản phẩm"); const { token } = useAuth(); const { productId } = useParams(); const location = useLocation();
  const [options, setOptions] = useState({ categories: [], brands: [], sizes: [], colors: [] }); const [product, setProduct] = useState(null); const [form, setForm] = useState(null); const [error, setError] = useState(null); const [success, setSuccess] = useState(location.state?.message ?? null); const [fields, setFields] = useState({}); const [busy, setBusy] = useState(false); const [removeTarget, setRemoveTarget] = useState(null);
  useEffect(() => { let active = true; Promise.all([adminProductsApi.detail(token, productId), adminProductsApi.options(token)]).then(([detail, productOptions]) => { if (active) { setProduct(detail.product); setForm(formValue(detail.product)); setOptions(productOptions); } }).catch((requestError) => { if (active) setError(requestError.message); }); return () => { active = false; }; }, [token, productId]);
  function apply(next, message) { setProduct(next); setForm(formValue(next)); setSuccess(message); setError(null); }
  async function run(action, message) { setBusy(true); setError(null); try { apply((await action()).product, message); } catch (requestError) { setError(requestError.message); setFields(requestError.fields ?? {}); } finally { setBusy(false); } }
  async function saveCore(event) { event.preventDefault(); await run(() => adminProductsApi.update(token, productId, { ...form, categoryId: Number(form.categoryId), brandId: Number(form.brandId), price: Number(form.price), salePrice: form.salePrice ? Number(form.salePrice) : null, badgeLabel: form.badgeLabel || null }), "Đã lưu thông tin sản phẩm."); }
  if (!product || !form) return <p role={error ? "alert" : "status"}>{error ?? "Đang tải sản phẩm..."}</p>;
  return <section className="mx-auto grid max-w-6xl gap-6"><div><Link className="text-sm font-semibold text-cobalt" to="/admin/san-pham">← Danh sách sản phẩm</Link><h1 className="mt-3 font-display text-3xl font-black">Sửa sản phẩm</h1><p className="mt-2 text-sm text-slate-600">Slug bất biến: <code>{product.slug}</code></p></div>{error ? <p role="alert" className="rounded-lg bg-coral/10 p-3 text-coral">{error}</p> : null}{success ? <p role="status" className="rounded-lg bg-mint/15 p-3 text-emerald-800">{success}</p> : null}<form className="rounded-xl border border-white/60 bg-white/75 p-5" onSubmit={saveCore}><ProductForm value={form} options={options} errors={fields} disabled={busy} onChange={setForm}/><button className="mt-5 min-h-11 rounded-lg bg-cobalt px-5 font-bold text-white disabled:opacity-60" disabled={busy}>{busy ? "Đang lưu..." : "Lưu thông tin"}</button></form><ImageManager images={product.images} busy={busy} onUpload={(files) => run(() => adminProductsApi.addImages(token, productId, files), "Đã thêm ảnh.")} onMove={(index, direction) => { const ids = product.images.map((image) => image.id); [ids[index], ids[index + direction]] = [ids[index + direction], ids[index]]; run(() => adminProductsApi.reorderImages(token, productId, ids), "Đã đổi thứ tự ảnh."); }} onRemove={(image) => setRemoveTarget({ type: "image", item: image })}/><VariantManager variants={product.variants} options={options} busy={busy} onAdd={(input) => run(() => adminProductsApi.addVariant(token, productId, input), "Đã thêm hoặc khôi phục biến thể.")} onUpdate={(id, stock) => run(() => adminProductsApi.updateVariant(token, productId, id, stock), "Đã cập nhật tồn kho.")} onRemove={(variant) => setRemoveTarget({ type: "variant", item: variant })}/><ConfirmDialog open={Boolean(removeTarget)} title={removeTarget?.type === "image" ? "Gỡ ảnh khỏi sản phẩm?" : "Xóa mềm biến thể?"} description={removeTarget?.type === "image" ? "Bản ghi ảnh sẽ bị gỡ nhưng file vật lý vẫn được giữ." : "Biến thể sẽ không còn bán nhưng vẫn được giữ để tham chiếu đơn cũ."} busy={busy} onCancel={() => setRemoveTarget(null)} onConfirm={async () => { const target = removeTarget; setRemoveTarget(null); if (target.type === "image") { setBusy(true); try { await adminProductsApi.removeImage(token, productId, target.item.id); const detail = await adminProductsApi.detail(token, productId); apply(detail.product, "Đã gỡ ảnh."); } catch (requestError) { setError(requestError.message); } finally { setBusy(false); } } else { setBusy(true); try { await adminProductsApi.removeVariant(token, productId, target.item.id); const detail = await adminProductsApi.detail(token, productId); apply(detail.product, "Đã xóa mềm biến thể."); } catch (requestError) { setError(requestError.message); } finally { setBusy(false); } } }}/></section>;
}
